version: '3.8'
services:
  app:
    image: shahraizq/documind:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      BASE_URL: "http://host.docker.internal:1234/v1"
    networks:
      - custom_bridge

networks:
  custom_bridge:
    driver: bridge
